Barbara's changes to the Our Community Block
stanford-earth/stanford_earth_helper pull request #5
Opened 2017-10-10 19:47 UTC by buttonwillowsix

This is a couple of simple text edits, two new images, and two images swapped. Also, haven't done a pull request in ages, so hoping this is right!

2017-10-10 19:59 UTC, sherakama commented on package.json
> +  "devDependencies": {
Hey Dena,

Grunt and the other libraries are already listed as a dependency. They don't also need to be in the devDependencies for this.

2017-10-10 20:00 UTC, sherakama commented on modules/stanford_earth_mosaic_blocks/src/Plugin/Block/MosaicBlockDefault.php
> -            'quote' => $this->t('We face enormous hrdles as a society in dealing with a changing climate, over extraction of resources, and biodiversity loss. Still, I remain optimistic in our abilit
Ooops. Thanks for catching that.

2017-10-10 20:00 UTC, sherakama requested changes
Most of this looks good. Please remove the devDependencies. Also, is there a Jira ticket associated with this?

2017-10-10 20:01 UTC, sherakama commented
@buttonwillowsix

2017-10-10 22:45 UTC, buttonwillowsix commented
Oops! Sorry about those devDependencies. Will remove. I think that happened
when I was messing around with my local environment.

There is a Jira ticket associated with this, but I had no idea about how to
link them up!


*Dena DeBry*
*Buttonwillow•Six <http://www.buttonwillowsix.com>* LLC
dena@buttonwillowsix.com
<http://www.buttonwillowsix.com>
*(801) 252-6006*
*Skype:* denanatalie




On Tue, Oct 10, 2017 at 2:00 PM, Sherakama <notifications@github.com> wrote:

> *@sherakama* requested changes on this pull request.
>
> Most of this looks good. Please remove the devDependencies. Also, is there
> a Jira ticket associated with this?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/stanford-earth/stanford_earth_helper/pull/5#pullrequestreview-68407594>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAMh4VmXT91nHI-hNT58GgRQauKOpiJ4ks5sq8z6gaJpZM4P0edp>
> .
>

2017-10-10 23:13 UTC, sherakama commented
Our Jira and GitHub organizations can talk to each other if you use the smart commit syntax in your commit message. It goes:

(ticket id)(colon) (commit message)(ending punctuation) 
eg:
EARTH-432: Added some stuff.

Please remove the dev dependencies and I can merge.

2017-10-11 16:12 UTC, buttonwillowsix commented
@sherakama, Added two more commits  (one for removing the devDependencies and the other because I realized the alt tags were not updated.)

2017-10-11 16:21 UTC, sherakama approved these changes

2017-10-11 16:22 UTC, merged